app/ usr/share/kalibro-configuration/
bin/ usr/share/kalibro-configuration/
config/ usr/share/kalibro-configuration/
db/ usr/share/kalibro-configuration/
public/ usr/share/kalibro-configuration/

Rakefile usr/share/kalibro-configuration/
Capfile usr/share/kalibro-configuration/
Gemfile usr/share/kalibro-configuration/
.ruby-gemset usr/share/kalibro-configuration/
.ruby-version usr/share/kalibro-configuration/